# Generated by Django 3.2.1 on 2023-06-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_live', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('file1', models.FileField(blank=True, upload_to='product_files/')),
                ('file2', models.FileField(blank=True, upload_to='product_files/')),
                ('file3', models.FileField(blank=True, upload_to='product_files/')),
                ('file4', models.FileField(blank=True, upload_to='product_files/')),
                ('file5', models.FileField(blank=True, upload_to='product_files/')),
                ('file6', models.FileField(blank=True, upload_to='product_files/')),
                ('file7', models.FileField(blank=True, upload_to='product_files/')),
                ('file8', models.FileField(blank=True, upload_to='product_files/')),
                ('file9', models.FileField(blank=True, upload_to='product_files/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('shipping_charges', models.FloatField()),
                ('returns', models.IntegerField()),
                ('specifications', models.CharField(max_length=4096)),
                ('description', models.CharField(max_length=512)),
                ('base_price', models.FloatField()),
                ('deadline', models.DateField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
