# Generated by Django 3.2.1 on 2023-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='highest_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
