# Generated by Django 3.2.1 on 2023-06-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='time_posted',
            field=models.TimeField(auto_now_add=True, default='00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
