# Generated by Django 3.2.1 on 2023-06-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230623_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='time_posted',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
