# Generated by Django 3.2.1 on 2023-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230626_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('Cellphones and Tablets', 'Cellphones and Tablets'), ('Laptops and Computers', 'Laptops and Computers'), ('Electronic Gadgets', 'Electronic Gadgets'), ('Tech Accessories', 'Tech Accessories'), ('Electrical Appliances', 'Electrical Appliances'), ('Shoes and Footware', 'Shoes and Footware'), ('Watches and Accessories', 'Watches and Accessories'), ('Beauty and Cosmetics', 'Beauty and Cosmetics'), ('Books and Toys', 'Books and Toys'), ('Others', 'Others')], max_length=100, unique=True),
        ),
    ]
